# frozen_string_literal: true

require 'time'

task :hello do
  puts 'Hello Rake'
end

task :hello_name, [:name] do |_task, args|
  puts 'Hello ' + args[:name]
end

task :specs, [:tags] do |_task, args|
  time = Time.now.utc.iso8601.tr(':', '')
  report = "--format html --out=log/report_#{time}.html"
  sh "cucumber #{args[:tags]} #{report}"
end
